import Booking from "../models/Booking.js";
import fs from "fs"; // Imported if you need to delete files on error

// Helper to generate a random Booking ID
const generateBookingId = () => {
  return "ACE" + Math.floor(100000 + Math.random() * 900000);
};

/* =========================================
   CREATE BOOKING (Local Storage Version)
========================================= */

export const createBooking = async (req, res) => {
  try {
    if (!req.body.payload) {
      return res.status(400).json({ message: "Missing payload data" });
    }

    // 1. Determine User ID
    const userId = req.user ? req.user._id : "USER_123";

    const payloadData = JSON.parse(req.body.payload);
    const uploadedFiles = req.files;

    // 2. Map Files
    if (uploadedFiles && uploadedFiles.length > 0 && payloadData.documents) {
      payloadData.documents = payloadData.documents.map((doc, index) => {
        const file = uploadedFiles.find(
          (f) => f.fieldname === `documents[${index}]`,
        );

        if (file) {
          const extension = file.originalname.split(".").pop();

          // Determine clean document display name
          const docName =
            doc.type === "OTHER"
              ? (doc.otherName || "Document").replace(/\s+/g, "_")
              : doc.type;

          // Note: The physical file on disk has the unique name generated by Multer.
          // 'finalFileName' is just for the frontend to show a pretty name.
          const finalFileName = `${userId}_${docName}.${extension}`;

          // IMPORTANT: Normalize path for URL (replace backslashes with forward slashes)
          // Result example: "uploads/bookings/documents[0]-1723456.pdf"
          const normalizedPath = file.path.replace(/\\/g, "/");

          return {
            ...doc,
            fileName: finalFileName, // Pretty name for UI
            filePath: normalizedPath, // Relative path for <img> src or download link
            mimeType: file.mimetype,
          };
        }
        return doc;
      });
    }

    // 3. Create Record
    const newBooking = new Booking({
      ...payloadData,
      bookingId: generateBookingId(),
      userId: userId,
      status: "PENDING",
    });

    await newBooking.save();

    res.status(200).json({
      message: "Booking created successfully",
      statusCode: 200,
      bookingId: newBooking.bookingId,
      data: newBooking,
    });
  } catch (error) {
    console.error("Create Booking Error:", error);
    res.status(500).json({ message: "Server error", error: error.message });
  }
};

/* =========================================
   GET USER BOOKINGS
========================================= */
export const getUserBookings = async (req, res) => {
  try {
    const bookings = await Booking.find().sort({ createdAt: -1 }).lean();

    res.status(200).json({
      statusCode: 200,
      count: bookings.length,
      data: bookings,
    });
  } catch (error) {
    console.error("Fetch Bookings Error:", error);
    res.status(500).json({
      message: "Fetch failed",
      error: error.message,
    });
  }
};
